### ISSUE TITLE
【feat】请求新增 AudioContext

### ISSUE THREAD

**Issue by Krimiston** [gxm11/RGModern#6]
AudioContext：对ruby脚本可见的音频上下文对象，一个对象对应一段音频实例，可以通过脚本即时获取该音频相关的信息、状态，以及控制。

**Comment by Krimiston** [comment]
补充，预期的效果如下：
新增 `Audio#BGM`、`Audio#ME` 等等子类，或是将 `Audio` 用作类并新增 `type` 属性；`Audio#bgm_play` 等等方法，在播放音频的同时，返回对应的类实例；返回的实例具有原始文件名、文件格式、音频长度、采样率等等属性，以及当前播放状态、当前播放坐标等等状态方法，还有播放、暂停、设置坐标等等控制方法，都能即时生效。

RGSS 标准没有定义 `Audio#bgm_play` 等等方法的返回值，所以可以大胆放心用。

`Audio` 由模块改成类有微小的可能性导致不兼容，因此优先考虑新增子类的方式。

**Comment by gxm11** [comment]
已经用另一套方案完成。
 - 定义了RGM::Music类，对应于c++中的cen::music类，此类封装了SDL_Mixer中的music相关函数；
 - 定义了RGM::Sound类，对应于c++中cen::sound_effect类，此类封装了SDL_Mixer中sound相关函数；
 - 在RGM::Music和RGM::Sound的基础上定义了Audio的Music_Manager类和Sound_Manager类，用来管理BGM/ME/BGS/SE；
 - 在Audio的Music_Manager类和Sound_Manager类的基础上定义了Audio#bgm_play等模块方法。

关于预期效果：
> 新增 Audio#BGM、Audio#ME 等等子类，或是将 Audio 用作类并新增 type 属性；Audio#bgm_play 等等方法，在播放音频的同时，返回对应的类实例；返回的实例具有原始文件名、文件格式、音频长度、采样率等等属性，以及当前播放状态、当前播放坐标等等状态方法，还有播放、暂停、设置坐标等等控制方法，都能即时生效。

可能SDL_Mixer对音频实例的控制没有那么精细，RGM已经尽量做到最好了。目前可以获得原始文件名、文件格式，当前播放状态、当前播放坐标，执行播放、暂停、设置坐标等等控制方法。不过RGM的异步框架，使得这些控制在音频线程的异步执行，可能不是那么即时，但是应该满足常见场合需求。
